import { useEffect, useState, type FormEvent } from 'react'
import { chooseFolder } from '../services/folderPicker'
import { cancelScan, getScanStatus, pauseScan, resumeScan, startScan } from '../services/scan'
import type { ScanJobSnapshot, ScanSummary } from '../types/scan'

function formatBytes(bytes: number) { if (!bytes) return '0 B'; const units=['B','KB','MB','GB','TB']; const unit=Math.min(Math.floor(Math.log(bytes)/Math.log(1024)),units.length-1); return `${(bytes/1024**unit).toFixed(unit===0?0:1)} ${units[unit]}` }
const active = (job: ScanJobSnapshot | null) => job?.status === 'running' || job?.status === 'paused'

export function AsyncScanView() {
  const [path,setPath]=useState(''); const [job,setJob]=useState<ScanJobSnapshot|null>(null); const [result,setResult]=useState<ScanSummary|null>(null); const [error,setError]=useState(''); const [picking,setPicking]=useState(false)
  useEffect(()=>{ if(!job || !active(job)) return; const timer=window.setTimeout(async()=>{ try { const next=await getScanStatus(job.id); setJob(next); if(next.status==='completed') setResult(next.result); if(next.status==='failed') setError(next.error??'スキャンに失敗しました') } catch(reason){ setError(reason instanceof Error?reason.message:String(reason)) } },250); return()=>window.clearTimeout(timer) },[job])
  const pick=async()=>{ setPicking(true); setError(''); try{ const selected=await chooseFolder(); if(selected)setPath(selected) }catch(reason){setError(reason instanceof Error?reason.message:String(reason))}finally{setPicking(false)} }
  const begin=async(event:FormEvent)=>{ event.preventDefault(); setError(''); setResult(null); try{ setJob(await startScan(path)) }catch(reason){setError(reason instanceof Error?reason.message:String(reason))} }
  const control=async(action:'pause'|'resume'|'cancel')=>{ if(!job)return; try{ const next=action==='pause'?await pauseScan(job.id):action==='resume'?await resumeScan(job.id):await cancelScan(job.id); setJob(next) }catch(reason){setError(reason instanceof Error?reason.message:String(reason))} }
  const summary=result??job
  return <div className="mock-stack"><section className="panel scan-card"><span className="eyebrow">読み取り専用・非同期スキャン</span><h2>フォルダを分析</h2><p>バックグラウンドで集計し、実行中でも一時停止またはキャンセルできます。</p><form className="scan-form" onSubmit={begin}><label htmlFor="scan-path">スキャン対象</label><div className="scan-path-row"><input id="scan-path" value={path} onChange={event=>setPath(event.target.value)} placeholder={navigator.platform.startsWith('Win')?'C:\\Users\\name\\Documents':'/Users/name/Documents'} autoComplete="off" disabled={active(job)}/><button className="secondary-button" type="button" disabled={picking||active(job)} onClick={pick}>{picking?'選択中…':'フォルダを選択'}</button></div><button className="primary-button" type="submit" disabled={picking||active(job)||!path.trim()}>スキャン開始</button></form>{job&&<div className="scan-progress" aria-live="polite"><div><strong>{job.status==='paused'?'一時停止中':job.status==='cancelled'?'キャンセル済み':job.status==='completed'?'完了':'スキャン中'}</strong><span>{job.currentPath||job.path}</span></div>{job.status==='running'&&<button type="button" className="secondary-button" onClick={()=>control('pause')}>一時停止</button>}{job.status==='paused'&&<button type="button" className="secondary-button" onClick={()=>control('resume')}>再開</button>}{active(job)&&<button type="button" className="secondary-button danger-button" onClick={()=>control('cancel')}>キャンセル</button>}</div>}{error&&<p className="scan-error" role="alert">{error}</p>}</section>{summary&&<section className="scan-result-summary" aria-label="スキャン進捗"><article><span>検出サイズ</span><strong>{formatBytes(summary.totalSizeBytes)}</strong></article><article><span>ファイル</span><strong>{summary.fileCount.toLocaleString()}</strong></article><article><span>フォルダ</span><strong>{summary.directoryCount.toLocaleString()}</strong></article><article><span>読み飛ばし</span><strong>{summary.skippedCount.toLocaleString()}</strong></article></section>}{result&&<section className="panel mock-panel"><div className="mock-header"><span className="eyebrow">スキャン結果</span><h2>{result.rootPath}</h2></div><table><thead><tr><th>名前</th><th>場所</th><th>サイズ</th><th>状態</th></tr></thead><tbody>{result.entries.map(entry=><tr key={entry.path}><td><strong>{entry.name}</strong></td><td>{entry.path}</td><td>{formatBytes(entry.sizeBytes)}</td><td>{entry.isDirectory?`${entry.fileCount.toLocaleString()}項目`:'ファイル'}</td></tr>)}</tbody></table></section>}</div>
}
